services:
  db:
    image: postgres:18.0-alpine3.22
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:19.0-20251021
    container_name: odoo_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - odoo-config:/etc/odoo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069/web/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
  odoo-config:
    driver: local

# Run containers
# Command: docker compose up -d

# Turn off containers
# Command: docker compose down

# Turn off and remove containers, networks, and volumes
# Command: docker compose down -v

# Access Odoo at http://localhost:8069
# - Master Password: Odoo@123
# - Database Name: alta_plastic
# - Email: admin@altaplastic.com
# - Password: secret
# - Language: English
# - Country: Vietnam
# - Demo Data: Load demonstration data